export const courses = [
  {
    id: 1,
    courseName: 'HTML CSS từ Zero đến Hero',
    title: 'Bài 1: Giới thiệu HTML',
    category: 'Lập trình',
    duration: '14:45',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/ge9wR8QWqeg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ge9wR8QWqeg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-500 to-purple-600',
  },
  {
    id: 2,
    courseName: 'HTML CSS từ Zero đến Hero',
    title: 'Bài 2: Các thẻ HTML cơ bản',
    category: 'Lập trình',
    duration: '12:30',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/ry6jYpx8QX4?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ry6jYpx8QX4/hqdefault.jpg',
    image: 'bg-gradient-to-r from-purple-600 to-pink-500',
  },
  {
    id: 3,
    courseName: 'HTML CSS từ Zero đến Hero',
    title: 'Bài 3: CSS Basics',
    category: 'Lập trình',
    duration: '18:15',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/Udc6MAAZT30?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/Udc6MAAZT30/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-600 to-purple-500',
  },
  {
    id: 4,
    courseName: 'JavaScript Cơ Bản',
    title: 'Bài 1: Biến và Kiểu Dữ Liệu',
    category: 'Lập trình',
    duration: '16:45',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/3s1r_g_jXNs?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/3s1r_g_jXNs/hqdefault.jpg',
    image: 'bg-gradient-to-r from-purple-500 to-pink-600',
  },
  {
    id: 5,
    courseName: 'React Cho Người Mới',
    title: 'Bài 1: Làm quen với React',
    category: 'Lập trình',
    duration: '20:00',
    tag: 'PRO',
    videoUrl: 'https://www.youtube.com/embed/hnfd5p7NUVg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/hnfd5p7NUVg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-400 to-purple-400',
  },
  {
    id: 6,
    courseName: 'HTML CSS từ Zero đến Hero',
    title: 'Bài 4: CSS Layout - Flexbox',
    category: 'Lập trình',
    duration: '22:15',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/xFONPDwW-lU?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/xFONPDwW-lU/hqdefault.jpg',
    image: 'bg-gradient-to-r from-purple-400 to-pink-600',
  },
  {
    id: 7,
    courseName: 'HTML CSS từ Zero đến Hero',
    title: 'Bài 5: Responsive Design',
    category: 'Lập trình',
    duration: '19:30',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/o5NHDzGV5o4?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/o5NHDzGV5o4/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-500 to-purple-500',
  },
  {
    id: 8,
    courseName: 'JavaScript Cơ Bản',
    title: 'Bài 2: Hàm và Scope',
    category: 'Lập trình',
    duration: '25:10',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/ge9wR8QWqeg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ge9wR8QWqeg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-600 to-purple-400',
  },
  {
    id: 9,
    courseName: 'JavaScript Cơ Bản',
    title: 'Bài 3: Array và Object',
    category: 'Lập trình',
    duration: '23:45',
    tag: 'FREE',
    videoUrl: 'https://www.youtube.com/embed/ge9wR8QWqeg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ge9wR8QWqeg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-purple-600 to-pink-400',
  },
  {
    id: 10,
    courseName: 'React Cho Người Mới',
    title: 'Bài 2: Component và Props',
    category: 'Lập trình',
    duration: '28:20',
    tag: 'PRO',
    videoUrl: 'https://www.youtube.com/embed/ge9wR8QWqeg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ge9wR8QWqeg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-pink-500 to-purple-500',
  },
  {
    id: 11,
    courseName: 'React Cho Người Mới',
    title: 'Bài 3: State và Hooks',
    category: 'Lập trình',
    duration: '26:50',
    tag: 'PRO',
    videoUrl: 'https://www.youtube.com/embed/ge9wR8QWqeg?rel=0&modestbranding=1',
    thumbnail: 'https://img.youtube.com/vi/ge9wR8QWqeg/hqdefault.jpg',
    image: 'bg-gradient-to-r from-purple-500 to-pink-600',
  },
];
